# Generated by Django 3.2.5 on 2021-08-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_rename_name_contact_reg_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_add_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents')),
                ('password', models.CharField(max_length=100)),
                ('conformpassword', models.CharField(max_length=100)),
                ('selectgroup', models.CharField(max_length=100)),
                ('Examplemultipleselect', models.CharField(max_length=100)),
            ],
        ),
    ]
