# Generated by Django 3.2.5 on 2021-08-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_user_add_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_add_database',
            old_name='email',
            new_name='email_id',
        ),
    ]
