# Generated by Django 3.2.5 on 2021-08-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_rename_email_user_add_database_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_add_database',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
