# Generated by Django 3.2.5 on 2021-08-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_rename_email_id_user_add_database_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_add_database',
            old_name='Examplemultipleselect',
            new_name='confirmpassword',
        ),
        migrations.RenameField(
            model_name='user_add_database',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='user_add_database',
            old_name='conformpassword',
            new_name='selectstate1',
        ),
        migrations.RenameField(
            model_name='user_add_database',
            old_name='selectgroup',
            new_name='selectstate2',
        ),
        migrations.RenameField(
            model_name='user_add_database',
            old_name='file',
            new_name='user_management_add_file',
        ),
    ]
