# Generated by Django 3.2.5 on 2021-08-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_auto_20210804_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_add_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categoryaddfile', models.FileField(upload_to='documents')),
                ('parentcategory', models.CharField(max_length=100)),
            ],
        ),
    ]
