# Generated by Django 3.2.5 on 2021-08-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_category_add_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_add_database',
            old_name='categoryaddfile',
            new_name='category_add_file',
        ),
    ]
