# Generated by Django 3.2.5 on 2021-08-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_rename_categoryaddfile_category_add_database_category_add_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_add_database',
            old_name='parentcategory',
            new_name='parent_category',
        ),
    ]
