# Generated by Django 3.2.5 on 2021-08-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_rename_parentcategory_category_add_database_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit_list_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
