# Generated by Django 3.2.5 on 2021-08-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0012_unit_list_database'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unit_list_database',
            new_name='unit_add_database',
        ),
    ]
