# Generated by Django 3.2.5 on 2021-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_rename_unit_list_database_unit_add_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='tax_add_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
            ],
        ),
    ]
