# Generated by Django 3.2.5 on 2021-08-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_tax_add_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_add_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_Category', models.CharField(max_length=100)),
                ('select_brand', models.CharField(max_length=100)),
                ('select_unit', models.CharField(max_length=100)),
                ('enter_barcode', models.CharField(max_length=100)),
                ('product_cost', models.CharField(max_length=100)),
                ('product_sales_price', models.CharField(max_length=100)),
                ('product_alert_quantatity', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=100)),
                ('tax_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
            ],
        ),
    ]
