# Generated by Django 3.2.5 on 2021-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0016_remove_product_add_database_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='quo_add_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_warehouse', models.CharField(max_length=100)),
                ('to_warhouse', models.CharField(max_length=100)),
                ('shippping_cost', models.CharField(max_length=100)),
                ('select_state', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantatity', models.CharField(max_length=100)),
                ('unit_price', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=100)),
            ],
        ),
    ]
