# Generated by Django 3.2.5 on 2021-08-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0017_quo_add_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_add_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_warehouse', models.CharField(max_length=100)),
                ('select_supplier', models.CharField(max_length=100)),
                ('select_state', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantatity', models.CharField(max_length=100)),
                ('unit_price', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=100)),
            ],
        ),
    ]
